# Generated by Django 3.2.8 on 2021-10-22 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento_Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('resultado', models.BooleanField(verbose_name='Resultado')),
                ('Equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo', verbose_name='Equipo')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimientos.mantenimiento', verbose_name='Mantenimiento')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='mantenimiento',
            field=models.ManyToManyField(through='equipos.Mantenimiento_Equipos', to='mantenimientos.Mantenimiento'),
        ),
    ]
